<?php

namespace App\Http\Requests\Brandname;

use App\Enums\Telco;
use App\Enums\SMSType;
use App\Enums\Provider;
use Illuminate\Validation\Rule;
use App\Rules\CountryAlpha2CodeRule;
use App\Rules\CostLessThanPriceRules;
use Illuminate\Foundation\Http\FormRequest;




class BrandnameConfigRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules()
    {
        return
            [
                //general
                'vinaphone' => 'required|array',
                'viettel' => 'required|array',
                'mobifone' => 'required|array',
                'vietnamemobile' => 'required|array',
                'gmobile' => 'required|array',
                'itelecom' => 'required|array',
                'reddi' => 'required|array',
                'other' => 'required|array',

                //vietnamemobile
                //provider st
                'vinaphone.st.region_code' => ['required', new CountryAlpha2CodeRule],
                'vinaphone.st.is_unicode' => 'required|boolean',
                'vinaphone.st.is_encrypted' => 'required|boolean',
                'vinaphone.st.pricings.cskh' => 'required|array',
                'vinaphone.st.pricings.cskh.*.from_sms_qty' => 'required|integer',
                'vinaphone.st.pricings.cskh.*.to_sms_qty' => 'required|integer',
                'vinaphone.st.pricings.cskh.*.price_per_sms' => 'required|numeric',
                'vinaphone.st.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                'vinaphone.st.pricings.qc' => 'required|array',
                'vinaphone.st.pricings.qc.*.from_sms_qty' => 'required|integer',
                'vinaphone.st.pricings.qc.*.to_sms_qty' => 'required|integer',
                'vinaphone.st.pricings.qc.*.price_per_sms' => 'required|numeric',
                'vinaphone.st.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vg
                // 'vinaphone.vg.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vinaphone.vg.is_unicode' => 'required|boolean',
                // 'vinaphone.vg.is_encrypted' => 'required|boolean',
                // 'vinaphone.vg.pricings.cskh' => 'required|array',
                // 'vinaphone.vg.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.vg.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.vg.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.vg.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vinaphone.vg.pricings.qc' => 'required|array',
                // 'vinaphone.vg.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.vg.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.vg.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.vg.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider tl
                // 'vinaphone.tl.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vinaphone.tl.is_unicode' => 'required|boolean',
                // 'vinaphone.tl.is_encrypted' => 'required|boolean',
                // 'vinaphone.tl.pricings.cskh' => 'required|array',
                // 'vinaphone.tl.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.tl.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.tl.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.tl.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vinaphone.tl.pricings.qc' => 'required|array',
                // 'vinaphone.tl.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.tl.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.tl.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.tl.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vm
                // 'vinaphone.vm.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vinaphone.vm.is_unicode' => 'required|boolean',
                // 'vinaphone.vm.is_encrypted' => 'required|boolean',
                // 'vinaphone.vm.pricings.cskh' => 'required|array',
                // 'vinaphone.vm.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.vm.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.vm.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.vm.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vinaphone.vm.pricings.qc' => 'required|array',
                // 'vinaphone.vm.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.vm.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.vm.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.vm.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider gp
                // 'vinaphone.gp.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vinaphone.gp.is_unicode' => 'required|boolean',
                // 'vinaphone.gp.is_encrypted' => 'required|boolean',
                // 'vinaphone.gp.pricings.cskh' => 'required|array',
                // 'vinaphone.gp.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.gp.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.gp.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.gp.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vinaphone.gp.pricings.qc' => 'required|array',
                // 'vinaphone.gp.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.gp.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.gp.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.gp.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider ht
                // 'vinaphone.ht.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vinaphone.ht.is_unicode' => 'required|boolean',
                // 'vinaphone.ht.is_encrypted' => 'required|boolean',
                // 'vinaphone.ht.pricings.cskh' => 'required|array',
                // 'vinaphone.ht.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.ht.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.ht.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.ht.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vinaphone.ht.pricings.qc' => 'required|array',
                // 'vinaphone.ht.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vinaphone.ht.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vinaphone.ht.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vinaphone.ht.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                //viettel
                //provider st
                'viettel.st.region_code' => ['required', new CountryAlpha2CodeRule],
                'viettel.st.is_unicode' => 'required|boolean',
                'viettel.st.is_encrypted' => 'required|boolean',
                'viettel.st.pricings' => 'required|array',
                'viettel.st.pricings.cskh' => 'required|array',
                'viettel.st.pricings.cskh.*.from_sms_qty' => 'required|integer',
                'viettel.st.pricings.cskh.*.to_sms_qty' => 'required|integer',
                'viettel.st.pricings.cskh.*.price_per_sms' => 'required|numeric',
                'viettel.st.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                'viettel.st.pricings.qc' => 'required|array',
                'viettel.st.pricings.qc.*.from_sms_qty' => 'required|integer',
                'viettel.st.pricings.qc.*.to_sms_qty' => 'required|integer',
                'viettel.st.pricings.qc.*.price_per_sms' => 'required|numeric',
                'viettel.st.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vg
                // 'viettel.vg.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'viettel.vg.is_unicode' => 'required|boolean',
                // 'viettel.vg.is_encrypted' => 'required|boolean',
                // 'viettel.vg.pricings' => 'required|array',
                // 'viettel.vg.pricings.cskh' => 'required|array',
                // 'viettel.vg.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'viettel.vg.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'viettel.vg.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'viettel.vg.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'viettel.vg.pricings.qc' => 'required|array',
                // 'viettel.vg.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'viettel.vg.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'viettel.vg.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'viettel.vg.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider tl
                // 'viettel.tl.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'viettel.tl.is_unicode' => 'required|boolean',
                // 'viettel.tl.is_encrypted' => 'required|boolean',
                // 'viettel.tl.pricings.cskh' => 'required|array',
                // 'viettel.tl.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'viettel.tl.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'viettel.tl.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'viettel.tl.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'viettel.tl.pricings.qc' => 'required|array',
                // 'viettel.tl.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'viettel.tl.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'viettel.tl.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'viettel.tl.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vm
                // 'viettel.vm.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'viettel.vm.is_unicode' => 'required|boolean',
                // 'viettel.vm.is_encrypted' => 'required|boolean',
                // 'viettel.vm.pricings.cskh' => 'required|array',
                // 'viettel.vm.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'viettel.vm.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'viettel.vm.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'viettel.vm.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'viettel.vm.pricings.qc' => 'required|array',
                // 'viettel.vm.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'viettel.vm.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'viettel.vm.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'viettel.vm.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider gp
                // 'viettel.gp.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'viettel.gp.is_unicode' => 'required|boolean',
                // 'viettel.gp.is_encrypted' => 'required|boolean',
                // 'viettel.gp.pricings.cskh' => 'required|array',
                // 'viettel.gp.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'viettel.gp.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'viettel.gp.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'viettel.gp.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'viettel.gp.pricings.qc' => 'required|array',
                // 'viettel.gp.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'viettel.gp.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'viettel.gp.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'viettel.gp.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider ht
                // 'viettel.ht.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'viettel.ht.is_unicode' => 'required|boolean',
                // 'viettel.ht.is_encrypted' => 'required|boolean',
                // 'viettel.ht.pricings.cskh' => 'required|array',
                // 'viettel.ht.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'viettel.ht.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'viettel.ht.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'viettel.ht.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'viettel.ht.pricings.qc' => 'required|array',
                // 'viettel.ht.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'viettel.ht.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'viettel.ht.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'viettel.ht.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                //mobifone
                //provider st
                'mobifone.st.region_code' => ['required', new CountryAlpha2CodeRule],
                'mobifone.st.is_unicode' => 'required|boolean',
                'mobifone.st.is_encrypted' => 'required|boolean',
                'mobifone.st.pricings.cskh' => 'required|array',
                'mobifone.st.pricings.cskh.*.from_sms_qty' => 'required|integer',
                'mobifone.st.pricings.cskh.*.to_sms_qty' => 'required|integer',
                'mobifone.st.pricings.cskh.*.price_per_sms' => 'required|numeric',
                'mobifone.st.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                'mobifone.st.pricings.qc' => 'required|array',
                'mobifone.st.pricings.qc.*.from_sms_qty' => 'required|integer',
                'mobifone.st.pricings.qc.*.to_sms_qty' => 'required|integer',
                'mobifone.st.pricings.qc.*.price_per_sms' => 'required|numeric',
                'mobifone.st.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vg
                // 'mobifone.vg.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'mobifone.vg.is_unicode' => 'required|boolean',
                // 'mobifone.vg.is_encrypted' => 'required|boolean',
                // 'mobifone.vg.pricings.cskh' => 'required|array',
                // 'mobifone.vg.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'mobifone.vg.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'mobifone.vg.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'mobifone.vg.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'mobifone.vg.pricings.qc' => 'required|array',
                // 'mobifone.vg.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'mobifone.vg.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'mobifone.vg.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'mobifone.vg.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider tl
                // 'mobifone.tl.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'mobifone.tl.is_unicode' => 'required|boolean',
                // 'mobifone.tl.is_encrypted' => 'required|boolean',
                // 'mobifone.tl.pricings.cskh' => 'required|array',
                // 'mobifone.tl.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'mobifone.tl.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'mobifone.tl.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'mobifone.tl.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'mobifone.tl.pricings.qc' => 'required|array',
                // 'mobifone.tl.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'mobifone.tl.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'mobifone.tl.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'mobifone.tl.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vm
                // 'mobifone.vm.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'mobifone.vm.is_unicode' => 'required|boolean',
                // 'mobifone.vm.is_encrypted' => 'required|boolean',
                // 'mobifone.vm.pricings.cskh' => 'required|array',
                // 'mobifone.vm.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'mobifone.vm.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'mobifone.vm.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'mobifone.vm.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'mobifone.vm.pricings.qc' => 'required|array',
                // 'mobifone.vm.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'mobifone.vm.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'mobifone.vm.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'mobifone.vm.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider gp
                // 'mobifone.gp.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'mobifone.gp.is_unicode' => 'required|boolean',
                // 'mobifone.gp.is_encrypted' => 'required|boolean',
                // 'mobifone.gp.pricings.cskh' => 'required|array',
                // 'mobifone.gp.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'mobifone.gp.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'mobifone.gp.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'mobifone.gp.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'mobifone.gp.pricings.qc' => 'required|array',
                // 'mobifone.gp.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'mobifone.gp.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'mobifone.gp.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'mobifone.gp.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider ht
                // 'mobifone.ht.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'mobifone.ht.is_unicode' => 'required|boolean',
                // 'mobifone.ht.is_encrypted' => 'required|boolean',
                // 'mobifone.ht.pricings.cskh' => 'required|array',
                // 'mobifone.ht.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'mobifone.ht.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'mobifone.ht.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'mobifone.ht.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'mobifone.ht.pricings.qc' => 'required|array',
                // 'mobifone.ht.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'mobifone.ht.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'mobifone.ht.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'mobifone.ht.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                //vietnamemobile
                //provider st
                'vietnamemobile.st.region_code' => ['required', new CountryAlpha2CodeRule],
                'vietnamemobile.st.is_unicode' => 'required|boolean',
                'vietnamemobile.st.is_encrypted' => 'required|boolean',
                'vietnamemobile.st.pricings.cskh' => 'required|array',
                'vietnamemobile.st.pricings.cskh.*.from_sms_qty' => 'required|integer',
                'vietnamemobile.st.pricings.cskh.*.to_sms_qty' => 'required|integer',
                'vietnamemobile.st.pricings.cskh.*.price_per_sms' => 'required|numeric',
                'vietnamemobile.st.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                'vietnamemobile.st.pricings.qc' => 'required|array',
                'vietnamemobile.st.pricings.qc.*.from_sms_qty' => 'required|integer',
                'vietnamemobile.st.pricings.qc.*.to_sms_qty' => 'required|integer',
                'vietnamemobile.st.pricings.qc.*.price_per_sms' => 'required|numeric',
                'vietnamemobile.st.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vg
                // 'vietnamemobile.vg.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vietnamemobile.vg.is_unicode' => 'required|boolean',
                // 'vietnamemobile.vg.is_encrypted' => 'required|boolean',
                // 'vietnamemobile.vg.pricings.cskh' => 'required|array',
                // 'vietnamemobile.vg.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.vg.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.vg.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.vg.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vietnamemobile.vg.pricings.qc' => 'required|array',
                // 'vietnamemobile.vg.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.vg.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.vg.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.vg.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider tl
                // 'vietnamemobile.tl.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vietnamemobile.tl.is_unicode' => 'required|boolean',
                // 'vietnamemobile.tl.is_encrypted' => 'required|boolean',
                // 'vietnamemobile.tl.pricings.cskh' => 'required|array',
                // 'vietnamemobile.tl.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.tl.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.tl.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.tl.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vietnamemobile.tl.pricings.qc' => 'required|array',
                // 'vietnamemobile.tl.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.tl.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.tl.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.tl.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vm
                // 'vietnamemobile.vm.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vietnamemobile.vm.is_unicode' => 'required|boolean',
                // 'vietnamemobile.vm.is_encrypted' => 'required|boolean',
                // 'vietnamemobile.vm.pricings.cskh' => 'required|array',
                // 'vietnamemobile.vm.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.vm.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.vm.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.vm.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vietnamemobile.vm.pricings.qc' => 'required|array',
                // 'vietnamemobile.vm.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.vm.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.vm.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.vm.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider gp
                // 'vietnamemobile.gp.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vietnamemobile.gp.is_unicode' => 'required|boolean',
                // 'vietnamemobile.gp.is_encrypted' => 'required|boolean',
                // 'vietnamemobile.gp.pricings.cskh' => 'required|array',
                // 'vietnamemobile.gp.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.gp.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.gp.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.gp.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vietnamemobile.gp.pricings.qc' => 'required|array',
                // 'vietnamemobile.gp.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.gp.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.gp.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.gp.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider ht
                // 'vietnamemobile.ht.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'vietnamemobile.ht.is_unicode' => 'required|boolean',
                // 'vietnamemobile.ht.is_encrypted' => 'required|boolean',
                // 'vietnamemobile.ht.pricings.cskh' => 'required|array',
                // 'vietnamemobile.ht.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.ht.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.ht.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.ht.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'vietnamemobile.ht.pricings.qc' => 'required|array',
                // 'vietnamemobile.ht.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'vietnamemobile.ht.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'vietnamemobile.ht.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'vietnamemobile.ht.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                //gmobile
                //provider st
                'gmobile.st.region_code' => ['required', new CountryAlpha2CodeRule],
                'gmobile.st.is_unicode' => 'required|boolean',
                'gmobile.st.is_encrypted' => 'required|boolean',
                'gmobile.st.pricings.cskh' => 'required|array',
                'gmobile.st.pricings.cskh.*.from_sms_qty' => 'required|integer',
                'gmobile.st.pricings.cskh.*.to_sms_qty' => 'required|integer',
                'gmobile.st.pricings.cskh.*.price_per_sms' => 'required|numeric',
                'gmobile.st.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                'gmobile.st.pricings.qc' => 'required|array',
                'gmobile.st.pricings.qc.*.from_sms_qty' => 'required|integer',
                'gmobile.st.pricings.qc.*.to_sms_qty' => 'required|integer',
                'gmobile.st.pricings.qc.*.price_per_sms' => 'required|numeric',
                'gmobile.st.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vg
                // 'gmobile.vg.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'gmobile.vg.is_unicode' => 'required|boolean',
                // 'gmobile.vg.is_encrypted' => 'required|boolean',
                // 'gmobile.vg.pricings.cskh' => 'required|array',
                // 'gmobile.vg.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'gmobile.vg.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'gmobile.vg.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'gmobile.vg.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'gmobile.vg.pricings.qc' => 'required|array',
                // 'gmobile.vg.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'gmobile.vg.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'gmobile.vg.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'gmobile.vg.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider tl
                // 'gmobile.tl.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'gmobile.tl.is_unicode' => 'required|boolean',
                // 'gmobile.tl.is_encrypted' => 'required|boolean',
                // 'gmobile.tl.pricings.cskh' => 'required|array',
                // 'gmobile.tl.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'gmobile.tl.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'gmobile.tl.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'gmobile.tl.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'gmobile.tl.pricings.qc' => 'required|array',
                // 'gmobile.tl.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'gmobile.tl.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'gmobile.tl.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'gmobile.tl.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vm
                // 'gmobile.vm.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'gmobile.vm.is_unicode' => 'required|boolean',
                // 'gmobile.vm.is_encrypted' => 'required|boolean',
                // 'gmobile.vm.pricings.cskh' => 'required|array',
                // 'gmobile.vm.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'gmobile.vm.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'gmobile.vm.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'gmobile.vm.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'gmobile.vm.pricings.qc' => 'required|array',
                // 'gmobile.vm.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'gmobile.vm.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'gmobile.vm.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'gmobile.vm.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider gp
                // 'gmobile.gp.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'gmobile.gp.is_unicode' => 'required|boolean',
                // 'gmobile.gp.is_encrypted' => 'required|boolean',
                // 'gmobile.gp.pricings.cskh' => 'required|array',
                // 'gmobile.gp.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'gmobile.gp.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'gmobile.gp.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'gmobile.gp.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'gmobile.gp.pricings.qc' => 'required|array',
                // 'gmobile.gp.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'gmobile.gp.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'gmobile.gp.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'gmobile.gp.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider ht
                // 'gmobile.ht.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'gmobile.ht.is_unicode' => 'required|boolean',
                // 'gmobile.ht.is_encrypted' => 'required|boolean',
                // 'gmobile.ht.pricings.cskh' => 'required|array',
                // 'gmobile.ht.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'gmobile.ht.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'gmobile.ht.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'gmobile.ht.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'gmobile.ht.pricings.qc' => 'required|array',
                // 'gmobile.ht.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'gmobile.ht.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'gmobile.ht.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'gmobile.ht.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                //itelecom
                //provider st
                'itelecom.st.region_code' => ['required', new CountryAlpha2CodeRule],
                'itelecom.st.is_unicode' => 'required|boolean',
                'itelecom.st.is_encrypted' => 'required|boolean',
                'itelecom.st.pricings.cskh' => 'required|array',
                'itelecom.st.pricings.cskh.*.from_sms_qty' => 'required|integer',
                'itelecom.st.pricings.cskh.*.to_sms_qty' => 'required|integer',
                'itelecom.st.pricings.cskh.*.price_per_sms' => 'required|numeric',
                'itelecom.st.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                'itelecom.st.pricings.qc' => 'required|array',
                'itelecom.st.pricings.qc.*.from_sms_qty' => 'required|integer',
                'itelecom.st.pricings.qc.*.to_sms_qty' => 'required|integer',
                'itelecom.st.pricings.qc.*.price_per_sms' => 'required|numeric',
                'itelecom.st.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vg
                // 'itelecom.vg.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'itelecom.vg.is_unicode' => 'required|boolean',
                // 'itelecom.vg.is_encrypted' => 'required|boolean',
                // 'itelecom.vg.pricings.cskh' => 'required|array',
                // 'itelecom.vg.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'itelecom.vg.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'itelecom.vg.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'itelecom.vg.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'itelecom.vg.pricings.qc' => 'required|array',
                // 'itelecom.vg.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'itelecom.vg.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'itelecom.vg.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'itelecom.vg.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider tl
                // 'itelecom.tl.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'itelecom.tl.is_unicode' => 'required|boolean',
                // 'itelecom.tl.is_encrypted' => 'required|boolean',
                // 'itelecom.tl.pricings.cskh' => 'required|array',
                // 'itelecom.tl.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'itelecom.tl.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'itelecom.tl.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'itelecom.tl.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'itelecom.tl.pricings.qc' => 'required|array',
                // 'itelecom.tl.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'itelecom.tl.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'itelecom.tl.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'itelecom.tl.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vm
                // 'itelecom.vm.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'itelecom.vm.is_unicode' => 'required|boolean',
                // 'itelecom.vm.is_encrypted' => 'required|boolean',
                // 'itelecom.vm.pricings.cskh' => 'required|array',
                // 'itelecom.vm.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'itelecom.vm.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'itelecom.vm.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'itelecom.vm.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'itelecom.vm.pricings.qc' => 'required|array',
                // 'itelecom.vm.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'itelecom.vm.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'itelecom.vm.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'itelecom.vm.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider gp
                // 'itelecom.gp.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'itelecom.gp.is_unicode' => 'required|boolean',
                // 'itelecom.gp.is_encrypted' => 'required|boolean',
                // 'itelecom.gp.pricings.cskh' => 'required|array',
                // 'itelecom.gp.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'itelecom.gp.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'itelecom.gp.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'itelecom.gp.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'itelecom.gp.pricings.qc' => 'required|array',
                // 'itelecom.gp.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'itelecom.gp.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'itelecom.gp.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'itelecom.gp.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider ht
                // 'itelecom.ht.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'itelecom.ht.is_unicode' => 'required|boolean',
                // 'itelecom.ht.is_encrypted' => 'required|boolean',
                // 'itelecom.ht.pricings.cskh' => 'required|array',
                // 'itelecom.ht.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'itelecom.ht.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'itelecom.ht.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'itelecom.ht.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'itelecom.ht.pricings.qc' => 'required|array',
                // 'itelecom.ht.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'itelecom.ht.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'itelecom.ht.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'itelecom.ht.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                //reddi
                //provider st
                'reddi.st.region_code' => ['required', new CountryAlpha2CodeRule],
                'reddi.st.is_unicode' => 'required|boolean',
                'reddi.st.is_encrypted' => 'required|boolean',
                'reddi.st.pricings.cskh' => 'required|array',
                'reddi.st.pricings.cskh.*.from_sms_qty' => 'required|integer',
                'reddi.st.pricings.cskh.*.to_sms_qty' => 'required|integer',
                'reddi.st.pricings.cskh.*.price_per_sms' => 'required|numeric',
                'reddi.st.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                'reddi.st.pricings.qc' => 'required|array',
                'reddi.st.pricings.qc.*.from_sms_qty' => 'required|integer',
                'reddi.st.pricings.qc.*.to_sms_qty' => 'required|integer',
                'reddi.st.pricings.qc.*.price_per_sms' => 'required|numeric',
                'reddi.st.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vg
                // 'reddi.vg.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'reddi.vg.is_unicode' => 'required|boolean',
                // 'reddi.vg.is_encrypted' => 'required|boolean',
                // 'reddi.vg.pricings.cskh' => 'required|array',
                // 'reddi.vg.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'reddi.vg.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'reddi.vg.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'reddi.vg.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'reddi.vg.pricings.qc' => 'required|array',
                // 'reddi.vg.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'reddi.vg.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'reddi.vg.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'reddi.vg.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider tl
                // 'reddi.tl.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'reddi.tl.is_unicode' => 'required|boolean',
                // 'reddi.tl.is_encrypted' => 'required|boolean',
                // 'reddi.tl.pricings.cskh' => 'required|array',
                // 'reddi.tl.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'reddi.tl.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'reddi.tl.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'reddi.tl.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'reddi.tl.pricings.qc' => 'required|array',
                // 'reddi.tl.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'reddi.tl.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'reddi.tl.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'reddi.tl.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vm
                // 'reddi.vm.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'reddi.vm.is_unicode' => 'required|boolean',
                // 'reddi.vm.is_encrypted' => 'required|boolean',
                // 'reddi.vm.pricings.cskh' => 'required|array',
                // 'reddi.vm.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'reddi.vm.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'reddi.vm.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'reddi.vm.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'reddi.vm.pricings.qc' => 'required|array',
                // 'reddi.vm.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'reddi.vm.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'reddi.vm.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'reddi.vm.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider gp
                // 'reddi.gp.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'reddi.gp.is_unicode' => 'required|boolean',
                // 'reddi.gp.is_encrypted' => 'required|boolean',
                // 'reddi.gp.pricings.cskh' => 'required|array',
                // 'reddi.gp.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'reddi.gp.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'reddi.gp.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'reddi.gp.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'reddi.gp.pricings.qc' => 'required|array',
                // 'reddi.gp.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'reddi.gp.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'reddi.gp.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'reddi.gp.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider ht
                // 'reddi.ht.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'reddi.ht.is_unicode' => 'required|boolean',
                // 'reddi.ht.is_encrypted' => 'required|boolean',
                // 'reddi.ht.pricings.cskh' => 'required|array',
                // 'reddi.ht.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'reddi.ht.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'reddi.ht.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'reddi.ht.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'reddi.ht.pricings.qc' => 'required|array',
                // 'reddi.ht.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'reddi.ht.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'reddi.ht.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'reddi.ht.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                //other
                //provider st
                'other.st.region_code' => ['required', new CountryAlpha2CodeRule],
                'other.st.is_unicode' => 'required|boolean',
                'other.st.is_encrypted' => 'required|boolean',
                'other.st.pricings.cskh.*.from_sms_qty' => 'required|integer',
                'other.st.pricings.cskh.*.to_sms_qty' => 'required|integer',
                'other.st.pricings.cskh.*.price_per_sms' => 'required|numeric',
                'other.st.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                'other.st.pricings.qc' => 'required|array',
                'other.st.pricings.qc.*.from_sms_qty' => 'required|integer',
                'other.st.pricings.qc.*.to_sms_qty' => 'required|integer',
                'other.st.pricings.qc.*.price_per_sms' => 'required|numeric',
                'other.st.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vg
                // 'other.vg.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'other.vg.is_unicode' => 'required|boolean',
                // 'other.vg.is_encrypted' => 'required|boolean',
                // 'other.vg.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'other.vg.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'other.vg.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'other.vg.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'other.vg.pricings.qc' => 'required|array',
                // 'other.vg.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'other.vg.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'other.vg.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'other.vg.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider tl
                // 'other.tl.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'other.tl.is_unicode' => 'required|boolean',
                // 'other.tl.is_encrypted' => 'required|boolean',
                // 'other.tl.pricings.cskh' => 'required|array',
                // 'other.tl.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'other.tl.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'other.tl.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'other.tl.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'other.tl.pricings.qc' => 'required|array',
                // 'other.tl.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'other.tl.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'other.tl.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'other.tl.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider vm
                // 'other.vm.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'other.vm.is_unicode' => 'required|boolean',
                // 'other.vm.is_encrypted' => 'required|boolean',
                // 'other.vm.pricings.cskh' => 'required|array',
                // 'other.vm.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'other.vm.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'other.vm.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'other.vm.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'other.vm.pricings.qc' => 'required|array',
                // 'other.vm.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'other.vm.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'other.vm.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'other.vm.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider gp
                // 'other.gp.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'other.gp.is_unicode' => 'required|boolean',
                // 'other.gp.is_encrypted' => 'required|boolean',
                // 'other.gp.pricings.cskh' => 'required|array',
                // 'other.gp.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'other.gp.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'other.gp.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'other.gp.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'other.gp.pricings.qc' => 'required|array',
                // 'other.gp.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'other.gp.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'other.gp.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'other.gp.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],

                // //provider ht
                // 'other.ht.region_code' => ['required', new CountryAlpha2CodeRule],
                // 'other.ht.is_unicode' => 'required|boolean',
                // 'other.ht.is_encrypted' => 'required|boolean',
                // 'other.ht.pricings.cskh' => 'required|array',
                // 'other.ht.pricings.cskh.*.from_sms_qty' => 'required|integer',
                // 'other.ht.pricings.cskh.*.to_sms_qty' => 'required|integer',
                // 'other.ht.pricings.cskh.*.price_per_sms' => 'required|numeric',
                // 'other.ht.pricings.cskh.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
                // 'other.ht.pricings.qc' => 'required|array',
                // 'other.ht.pricings.qc.*.from_sms_qty' => 'required|integer',
                // 'other.ht.pricings.qc.*.to_sms_qty' => 'required|integer',
                // 'other.ht.pricings.qc.*.price_per_sms' => 'required|numeric',
                // 'other.ht.pricings.qc.*.cost_per_sms' => ['required', 'numeric', new CostLessThanPriceRules],
            ];
    }
}
